import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy | Mahjic",
  description:
    "Privacy policy for Mahjic, the open rating system for American Mahjong, the Mahjic App, and the mahjic.org website.",
  alternates: {
    canonical: "/privacy",
  },
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-cream">
      {/* Header */}
      <div className="bg-aqua-soft border-b border-green/10">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-12">
          <p className="section-label">Legal</p>
          <h1 className="font-display text-3xl sm:text-4xl font-bold text-text">
            Privacy Policy
          </h1>
          <p className="mt-2 text-lg text-text-light">
            How we collect, use, and protect your information across the Mahjic
            ecosystem.
          </p>
        </div>
      </div>

      {/* Content */}
      <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 py-12">
        <p className="text-sm text-text-light mb-10">
          Effective date: February 6, 2026
        </p>

        <div className="space-y-10">
          {/* Introduction */}
          <section>
            <h2 className="font-display text-2xl font-bold text-text mb-4">
              Introduction
            </h2>
            <p className="text-text-light mb-4">
              This Privacy Policy describes how Mahjic (&quot;we,&quot;
              &quot;us,&quot; or &quot;our&quot;) collects, uses, and protects
              your personal information when you use:
            </p>
            <ul className="list-disc pl-6 text-text-light space-y-2">
              <li>
                <strong className="text-text">The Mahjic App</strong> &mdash;
                our iOS and Android mobile application for American Mahjong club
                management, event registration, and gameplay
              </li>
              <li>
                <strong className="text-text">mahjic.org</strong> &mdash; our
                website providing the open rating system for American Mahjong
              </li>
            </ul>
            <p className="text-text-light mt-4">
              Mahjic is part of the Bam Good Time ecosystem. The Mahjic App,
              mahjic.org, and bamgoodtime.com share a unified database and
              authentication system. This means your account and data are
              accessible across all three platforms. This policy covers data
              handling across all of them.
            </p>
          </section>

          {/* Information We Collect */}
          <section>
            <h2 className="font-display text-2xl font-bold text-text mb-4">
              Information We Collect
            </h2>

            <h3 className="font-display text-lg font-semibold text-text mb-3 mt-6">
              Account Information
            </h3>
            <ul className="list-disc pl-6 text-text-light space-y-2">
              <li>
                <strong className="text-text">Email address</strong> &mdash;
                used for passwordless authentication (magic link / OTP login)
              </li>
              <li>
                <strong className="text-text">Name</strong> &mdash; displayed on
                your player profile and leaderboard rankings
              </li>
              <li>
                <strong className="text-text">User ID</strong> &mdash;
                automatically generated by our authentication system to identify
                your account
              </li>
            </ul>

            <h3 className="font-display text-lg font-semibold text-text mb-3 mt-6">
              Gameplay and Rating Data
            </h3>
            <ul className="list-disc pl-6 text-text-light space-y-2">
              <li>
                <strong className="text-text">Game scores</strong> &mdash;
                submitted by Verified Sources (clubs and leagues) after gameplay
                sessions
              </li>
              <li>
                <strong className="text-text">Mahjic Rating</strong> &mdash;
                your ELO-based skill rating calculated from all submitted games
              </li>
              <li>
                <strong className="text-text">Verified Rating</strong> &mdash; a
                separate rating calculated only from games against other verified
                players
              </li>
              <li>
                <strong className="text-text">Rating history</strong> &mdash;
                historical record of your rating changes over time
              </li>
            </ul>

            <h3 className="font-display text-lg font-semibold text-text mb-3 mt-6">
              Event and Club Data
            </h3>
            <ul className="list-disc pl-6 text-text-light space-y-2">
              <li>
                <strong className="text-text">Event registrations</strong>{" "}
                &mdash; records of events you register for, including attendance
                and check-in status
              </li>
              <li>
                <strong className="text-text">Club membership</strong> &mdash;
                which clubs or leagues you are associated with
              </li>
              <li>
                <strong className="text-text">
                  Admin-imported contact information
                </strong>{" "}
                &mdash; club administrators may import member contact lists (such
                as CSV files) to manage their rosters
              </li>
            </ul>

            <h3 className="font-display text-lg font-semibold text-text mb-3 mt-6">
              Identity Verification Data
            </h3>
            <p className="text-text-light mb-2">
              To become a Verified Player ($20/year subscription), you must
              complete identity verification. This process involves:
            </p>
            <ul className="list-disc pl-6 text-text-light space-y-2">
              <li>
                <strong className="text-text">Government-issued ID</strong>{" "}
                &mdash; a photo of your ID document (driver&apos;s license,
                passport, etc.)
              </li>
              <li>
                <strong className="text-text">Selfie</strong> &mdash; a photo of
                your face for matching against your ID
              </li>
            </ul>
            <p className="text-text-light mt-3">
              <strong className="text-text">Important:</strong> Government ID
              images and selfies are collected and processed entirely by Stripe
              Identity. We never receive, store, or have access to your
              government ID images or biometric data. We only receive a
              pass/fail verification result from Stripe.
            </p>

            <h3 className="font-display text-lg font-semibold text-text mb-3 mt-6">
              Payment Information
            </h3>
            <p className="text-text-light">
              Payment processing for verified player subscriptions and paid
              events is handled entirely by Stripe. We do not collect, store, or
              have access to your credit card numbers, bank account details, or
              other payment credentials. Stripe provides us only with
              transaction confirmation and subscription status.
            </p>

            <h3 className="font-display text-lg font-semibold text-text mb-3 mt-6">
              Device and Technical Information
            </h3>
            <ul className="list-disc pl-6 text-text-light space-y-2">
              <li>
                <strong className="text-text">Push notification tokens</strong>{" "}
                &mdash; Expo push tokens stored when you opt in to push
                notifications on the Mahjic App, used solely to deliver
                notifications you have requested
              </li>
              <li>
                <strong className="text-text">Device information</strong>{" "}
                &mdash; basic device type and platform information necessary for
                delivering push notifications
              </li>
            </ul>

            <h3 className="font-display text-lg font-semibold text-text mb-3 mt-6">
              Uploaded Content
            </h3>
            <p className="text-text-light">
              Club administrators may upload photos and graphics for events (such
              as event flyers or promotional images). These are stored in our
              database and used only for the associated events.
            </p>
          </section>

          {/* How We Use Your Information */}
          <section>
            <h2 className="font-display text-2xl font-bold text-text mb-4">
              How We Use Your Information
            </h2>
            <p className="text-text-light mb-4">
              We use the information we collect for the following purposes:
            </p>
            <ul className="list-disc pl-6 text-text-light space-y-2">
              <li>
                To authenticate your identity and provide access to your account
              </li>
              <li>
                To calculate and maintain your Mahjic Rating and Verified Rating
              </li>
              <li>
                To display your profile and rankings on public leaderboards
                (verified players only)
              </li>
              <li>To manage event registrations, check-ins, and attendance</li>
              <li>
                To generate seating arrangements and table assignments for events
              </li>
              <li>
                To send push notifications you have opted into (event reminders,
                table assignments, waitlist updates)
              </li>
              <li>
                To process payments for verified player subscriptions and paid
                events
              </li>
              <li>
                To verify your identity for verified player status through
                Stripe Identity
              </li>
              <li>
                To send transactional emails (verification confirmations,
                subscription receipts)
              </li>
              <li>
                To maintain league standings, tournament results, and scoring
                history
              </li>
            </ul>
          </section>

          {/* Data Sharing Across the Ecosystem */}
          <section>
            <h2 className="font-display text-2xl font-bold text-text mb-4">
              Data Sharing Across the Mahjic Ecosystem
            </h2>
            <p className="text-text-light mb-4">
              The Mahjic App, mahjic.org, and Bam Good Time (bamgoodtime.com)
              share a single database and authentication system. This means:
            </p>
            <ul className="list-disc pl-6 text-text-light space-y-2">
              <li>
                Your account credentials work across all three platforms with a
                single login
              </li>
              <li>
                Game scores submitted through Bam Good Time are used to
                calculate your Mahjic Rating on mahjic.org
              </li>
              <li>
                Event registrations made in the Mahjic App are visible to club
                administrators on Bam Good Time
              </li>
              <li>
                Your player profile (name, ratings, verification status) is
                shared across all platforms
              </li>
            </ul>
            <p className="text-text-light mt-4">
              All three platforms are operated by the same team and governed by
              this privacy policy. We do not sell, rent, or share your personal
              data with unrelated third parties.
            </p>
          </section>

          {/* Third-Party Services */}
          <section>
            <h2 className="font-display text-2xl font-bold text-text mb-4">
              Third-Party Services
            </h2>
            <p className="text-text-light mb-4">
              We rely on the following trusted third-party services to operate
              the Mahjic ecosystem:
            </p>
            <ul className="list-disc pl-6 text-text-light space-y-3">
              <li>
                <strong className="text-text">Supabase</strong> &mdash; provides
                our database hosting, user authentication, and file storage.
                Your account data, game records, and uploaded content are stored
                on Supabase infrastructure. See the{" "}
                <a
                  href="https://supabase.com/privacy"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-green-deep hover:text-green underline"
                >
                  Supabase Privacy Policy
                </a>
                .
              </li>
              <li>
                <strong className="text-text">Stripe</strong> &mdash; handles
                payment processing for verified player subscriptions and paid
                events, as well as identity verification (government ID and
                selfie). Stripe operates as an independent data controller for
                payment and identity data. See the{" "}
                <a
                  href="https://stripe.com/privacy"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-green-deep hover:text-green underline"
                >
                  Stripe Privacy Policy
                </a>
                .
              </li>
              <li>
                <strong className="text-text">Expo</strong> &mdash; provides the
                push notification infrastructure for the Mahjic App. Expo push
                tokens are transmitted to Expo&apos;s servers to deliver
                notifications. See the{" "}
                <a
                  href="https://expo.dev/privacy"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-green-deep hover:text-green underline"
                >
                  Expo Privacy Policy
                </a>
                .
              </li>
              <li>
                <strong className="text-text">Resend</strong> &mdash; delivers
                transactional emails (verification confirmations, subscription
                receipts). Your email address is shared with Resend for this
                purpose.
              </li>
              <li>
                <strong className="text-text">Vercel</strong> &mdash; hosts the
                mahjic.org website. See the{" "}
                <a
                  href="https://vercel.com/legal/privacy-policy"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-green-deep hover:text-green underline"
                >
                  Vercel Privacy Policy
                </a>
                .
              </li>
            </ul>
          </section>

          {/* No Tracking, No Ads */}
          <section>
            <h2 className="font-display text-2xl font-bold text-text mb-4">
              No Tracking and No Advertising
            </h2>
            <p className="text-text-light mb-4">
              We do not use any third-party analytics, tracking pixels, or
              advertising networks. Specifically:
            </p>
            <ul className="list-disc pl-6 text-text-light space-y-2">
              <li>We do not run ads on any of our platforms</li>
              <li>
                We do not sell or share your data with advertisers or data
                brokers
              </li>
              <li>
                We do not use tracking cookies or cross-site tracking
                technologies
              </li>
              <li>
                We do not build advertising profiles based on your activity
              </li>
            </ul>
            <p className="text-text-light mt-4">
              We use only essential cookies to maintain your login session. No
              tracking or marketing cookies are used.
            </p>
          </section>

          {/* Data Security */}
          <section>
            <h2 className="font-display text-2xl font-bold text-text mb-4">
              Data Security
            </h2>
            <p className="text-text-light mb-4">
              We take the security of your data seriously and implement the
              following measures:
            </p>
            <ul className="list-disc pl-6 text-text-light space-y-2">
              <li>
                All connections between your device and our servers use SSL/TLS
                encryption (HTTPS)
              </li>
              <li>
                The mobile app implements SSL certificate pinning for additional
                connection security
              </li>
              <li>
                Authentication uses secure magic links and one-time passwords
                rather than stored passwords
              </li>
              <li>
                API keys for Verified Sources are securely generated and
                transmitted
              </li>
              <li>
                Payment and identity verification data is handled entirely by
                Stripe and never passes through our servers
              </li>
              <li>
                Database access is protected by row-level security policies
              </li>
            </ul>
          </section>

          {/* Push Notifications */}
          <section>
            <h2 className="font-display text-2xl font-bold text-text mb-4">
              Push Notifications
            </h2>
            <p className="text-text-light mb-4">
              Push notifications in the Mahjic App are entirely opt-in. You will
              be prompted to grant notification permissions when you first use
              the app. If you grant permission, we store an Expo push token
              associated with your account to deliver notifications such as:
            </p>
            <ul className="list-disc pl-6 text-text-light space-y-2">
              <li>Event reminders for events you are registered for</li>
              <li>Table assignment notifications when seating is generated</li>
              <li>
                Waitlist updates when you are promoted from a waitlist to a
                confirmed spot
              </li>
              <li>Score and rating updates after games are finalized</li>
            </ul>
            <p className="text-text-light mt-4">
              You can disable push notifications at any time through your
              device&apos;s system settings. Disabling notifications will not
              affect any other functionality of the app.
            </p>
          </section>

          {/* Data Retention */}
          <section>
            <h2 className="font-display text-2xl font-bold text-text mb-4">
              Data Retention
            </h2>
            <p className="text-text-light mb-4">
              We retain your data for as long as your account is active or as
              needed to provide our services:
            </p>
            <ul className="list-disc pl-6 text-text-light space-y-2">
              <li>
                <strong className="text-text">Account data</strong> is retained
                until you request deletion
              </li>
              <li>
                <strong className="text-text">Rating history</strong> is
                retained to maintain the integrity of the rating system and
                leaderboard rankings
              </li>
              <li>
                <strong className="text-text">Event and game data</strong> is
                retained for historical records and league standings
              </li>
              <li>
                <strong className="text-text">Push notification tokens</strong>{" "}
                are removed when you uninstall the app or revoke notification
                permissions
              </li>
              <li>
                <strong className="text-text">
                  Identity verification results
                </strong>{" "}
                (pass/fail status only) are retained as long as your verified
                subscription is active. Stripe retains identity documents
                according to their own retention policy.
              </li>
            </ul>
          </section>

          {/* Your Rights */}
          <section>
            <h2 className="font-display text-2xl font-bold text-text mb-4">
              Your Rights
            </h2>
            <p className="text-text-light mb-4">You have the right to:</p>
            <ul className="list-disc pl-6 text-text-light space-y-2">
              <li>
                <strong className="text-text">Access</strong> the personal data
                we hold about you
              </li>
              <li>
                <strong className="text-text">Correct</strong> inaccurate
                information in your profile
              </li>
              <li>
                <strong className="text-text">Delete</strong> your account and
                associated personal data
              </li>
              <li>
                <strong className="text-text">Export</strong> your data in a
                portable format
              </li>
              <li>
                <strong className="text-text">Opt out</strong> of push
                notifications at any time
              </li>
            </ul>
            <p className="text-text-light mt-4">
              To exercise any of these rights, please contact us at{" "}
              <a
                href="mailto:support@mahjic.org"
                className="text-green-deep hover:text-green underline"
              >
                support@mahjic.org
              </a>
              . We will respond to your request within 30 days.
            </p>
            <p className="text-text-light mt-3">
              Please note that deleting your account will remove your personal
              information, but anonymized game records and rating contributions
              may be retained to preserve the integrity of the rating system for
              other players.
            </p>
          </section>

          {/* Children's Privacy */}
          <section>
            <h2 className="font-display text-2xl font-bold text-text mb-4">
              Children&apos;s Privacy
            </h2>
            <p className="text-text-light">
              Our services are not directed to children under the age of 13. We
              do not knowingly collect personal information from children under
              13. If you are a parent or guardian and believe your child has
              provided us with personal information, please contact us at{" "}
              <a
                href="mailto:support@mahjic.org"
                className="text-green-deep hover:text-green underline"
              >
                support@mahjic.org
              </a>{" "}
              and we will promptly delete such information.
            </p>
          </section>

          {/* Changes to This Policy */}
          <section>
            <h2 className="font-display text-2xl font-bold text-text mb-4">
              Changes to This Policy
            </h2>
            <p className="text-text-light">
              We may update this privacy policy from time to time to reflect
              changes in our practices or applicable laws. When we make
              significant changes, we will update the effective date at the top
              of this page and, where appropriate, notify you via email or an
              in-app notification. We encourage you to review this policy
              periodically.
            </p>
          </section>

          {/* Contact Us */}
          <section>
            <h2 className="font-display text-2xl font-bold text-text mb-4">
              Contact Us
            </h2>
            <p className="text-text-light mb-4">
              If you have any questions about this privacy policy or how we
              handle your data, you can reach us at:
            </p>
            <ul className="list-disc pl-6 text-text-light space-y-2">
              <li>
                Email:{" "}
                <a
                  href="mailto:support@mahjic.org"
                  className="text-green-deep hover:text-green underline"
                >
                  support@mahjic.org
                </a>
              </li>
              <li>
                Website:{" "}
                <a
                  href="https://mahjic.org"
                  className="text-green-deep hover:text-green underline"
                >
                  mahjic.org
                </a>
              </li>
            </ul>
          </section>
        </div>
      </div>
    </div>
  );
}
